name: $(SourceBranchName)-$(Date:yyyyMMdd)-$(Rev:rrr)

resources:
  repositories:
  - repository: templates
    type: git
    name: az-pipeline-terraform
    ref: refs/heads/main

trigger:
  branches:
    include:
    - main
  paths:
   include:
     - /npe/*
     
pool: terraform-nonprod

stages:
  - template: terraform/terraform.yaml@templates
    parameters:
      TFEnvironment: 'nonprod'
      secureVarsFile: 'xxx-xxx.env'
      deploymentEnvironment: NPE-Infra
      terraformVersion: latest
